-- Active: 1762329389992@@127.0.0.1@5432@MeetTime-Group

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE Users(
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    nim VARCHAR(21) UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE Users;